### ISSUE TITLE
Immediate CTD

### ISSUE THREAD

**Issue by llloyd4** [llde/TESReloaded10#107]
Well... I have a preexisting install with mods. I downloaded the latest off of Nexus, seeing that the ENB and Stutter Remover will conflict I moved the Stutter Remover's .dll and .ini file out of the plugins folder into a backup folder ( just in case) and renamed the d3d9.dll to d3d9.bak (which disables it entirely) and clicked OBSE in NMM , the Oblivion Loader pops up, I click Play, black screen then a pop up saying it's crashed. 
[OblivionReloaded.log](https://github.com/llde/TESReloaded10/files/14745021/OblivionReloaded.log)
[obse.log](https://github.com/llde/TESReloaded10/files/14745022/obse.log)

Dunno what happened but I'm gonna have to disable it if I want to continue to play. >.<

**Comment by llde** [comment]
@llloyd4  you are missing the Cobb's Crash Logger, it's pratically the most important log.

**Comment by llloyd4** [comment]
Uh, not sure? 
https://pastebin.com/1aX2XQjX - My mods and their load order. 
Do you see anything? I didn't see either of those but... O.o

**Comment by llde** [comment]
@llloyd4  it's that. For some reason OR from version 8 crash when encountering edited  shaderpackages. I will try to solve this situation in OR11

**Comment by llloyd4** [comment]
Oh good, as I hate the default blue tinted night eye, I play a Khajiit usually so I have a night eye toggle and use night eye a lot in dungeons and Aylied ruins.

**Comment by llde** [comment]
Hi again @llloyd4 I did some investigation and it turns  that the crash is caused by 2 elements: OR doesn't expect CreateVertexShader to fail, and so it use directly the resulting object, and in the normal condition this in fact never happens. What do happen however is that when you install an OMOD with OBMM that edit shaderpakcages, the first shader in every touched shaderpackage get corrupt and loose its proper name, and this cause the function to fail.

For the time being I added in OR11 a check that warn the user in the log in this case, and bypass the failed shader. However I'm not sure if this situation can cause problems, but I think not if you use medium/high settings
